name: CI pipeline

on: 
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - "api/**"
      - "misc/**"
      - "web/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build latest
        run: |
          echo "Building non main branch"
          cat api/api.txt
          cat web/web.txt
          cat misc/misc.txt

      - name: Get Tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: build tagged version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo $RELEASE_VERSION
          echo "Building main branch"
          cat api/api.txt
          cat web/web.txt
          cat misc/misc.txt
          
    
     
