name: build web

on: 
  push:
    branches:
      - main
    paths:
      - "web/**"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
    paths:
      - "web/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: disaply content
         run: |
            cat web/web.txt
